#!/usr/bin/env node

var path = require('path')
  , fs = require('fs')
  , dir, paths = []
  , argv = process.argv;

if(argv.length == 2) {
  console.log('Usage: whitespaces [-c] [FILES]');
} else if (argv.length > 3 && argv[2] === "-c") {
  dir = process.cwd();
  for (var i=3; argv[i]; i++) {
    paths.push(path.resolve(dir, argv[i]));
  }

  paths.forEach(function (file) {
    fs.readFile(file, 'utf8', function (err, data) {
      if (err) return console.log('Reading', file, err);
      data.split("\n").forEach(function (line) {
        if (/\s+$/.test(line)) {
          console.error("Whitespace found.");
          process.exit(1);
        }
      });
    });
  });
}
else {
  dir = process.cwd();
  for (var i=2; argv[i]; i++) {
    paths.push(path.resolve(dir, argv[i]));
  }

  paths.forEach(function (file) {
    fs.readFile(file, 'utf8', function (err, data) {
      if (err) return console.log('Reading', file, err);
      data = data.split("\n").map(function (line) {
        if (/^\s*$/.test(line)) return '';
        return line.replace(/\s*$/, '');
      }).join("\n");
      fs.writeFile(file, data, 'utf8', function (err, data) {
        if (err) return console.log('Writing', file, err);
      });
    });
  });
}
